// apps/dashboard/components/modal.tsx
import { Dialog } from '@headlessui/react';

interface ModalProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  title?: string;
  children?: any;
}

export function Modal({ open, setOpen, title, children }: ModalProps) {
  // Prevent dumb TS errors
  const DialogFix = Dialog as any;
  const Title = Dialog.Title as any;
  const Description = Dialog.Description as any;

  return (
    <DialogFix
      as="div"
      open={open}
      className="fixed inset-0 z-10 overflow-y-auto bg-black bg-opacity-50"
      onClose={() => setOpen(false)}
    >
      <div className="min-h-screen px-4 text-center">
        <Dialog.Overlay className="fixed inset-0" />

        <div className="min-h-screen px-4 flex flex-col justify-center items-center">
          <div className="inline-block w-full max-w-lg p-6 overflow-hidden text-left align-middle transition-all transform bg-zinc-600 shadow-xl rounded-2xl">
            <Title as="h3" className="text-lg font-medium leading-6 text-white">
              {title}
            </Title>
            <Description className="mt-2 text-zinc-200">{children}</Description>
          </div>
        </div>
      </div>
    </DialogFix>
  );
}

// apps/dashboard/src/components/Modal.svelte
<script lang="ts">
  import { fade, scale } from 'svelte/transition';
  import Portal from 'svelte-portal';
  import { trapFocus } from 'trap-focus-svelte';

  import { cn } from '$lib/util';

  function onModalClick(this: any, e: any) {
    if (e.target === this && allowClose) onclose?.();
  }

  interface Props {
    allowClose?: boolean;
    children?: import('svelte').Snippet;
    class?: string;
    onclose?: () => void;
  }

  let { allowClose = true, class: wrapperClass, children, onclose }: Props = $props();
</script>

<Portal target="body">
  <div
    transition:fade={{ duration: 100 }}
    class="fixed top-0 right-0 bottom-0 left-0 z-30 flex items-center justify-center bg-black/40 px-2 backdrop-blur-sm select-none md:px-8"
    aria-hidden="true"
    onclick={onModalClick}
    use:trapFocus
  >
    <div
      transition:scale={{ duration: 250, opacity: 0, start: 0.95 }}
      class={cn(
        'relative inline-flex max-h-[calc(100svh-6rem)] w-[1024px] flex-col items-start justify-start overflow-hidden rounded-t-lg bg-zinc-900 text-zinc-300 shadow-lg ring-2 ring-black/50 md:rounded-b-lg',
        wrapperClass
      )}
    >
      {@render children?.()}
    </div>
  </div>
</Portal>
